# Generated by Django 2.1.5 on 2019-04-13 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0022_auto_20181028_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='summary',
            field=models.TextField(default='', help_text='Enter a brief description of the author', max_length=1000),
            preserve_default=False,
        ),
    ]
