# Generated by Django 2.1.5 on 2019-04-13 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0023_author_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='image',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
